export default [
    { name: 'OLS1', moves: `R2 D R' U' R D' R2 U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS2', moves: `R2 U2' R' U' R U' R' U2 R'`, mirror: false, invert: false },
    { name: 'OLS3', moves: `R U2' R' U2 R U2' R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS4', moves: `R2 U2' R' U' R U' R2' U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS5', moves: `R U R' U' R U2' R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS6', moves: `R U' R' U' R U R' U' R U2' R'`, mirror: false, invert: false },
    { name: 'OLS7', moves: `R U R D R' U2 R D' R2' U2' R U' R'`, mirror: false, invert: false },
    { name: 'OLS8', moves: `R U2 R' U2 R U R' U' R U2 R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS9', moves: `R U2' R' U R2 D R' U R D' R2'`, mirror: false, invert: false },
    { name: 'OLS10', moves: `R U2 R U R' U R U2' R2'`, mirror: false, invert: false },
    { name: 'OLS11', moves: `R U' R' U R U2' R' U2 R U2' R'`, mirror: false, invert: false },
    { name: 'OLS12', moves: `R U2' R' U R U' R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS13', moves: `R U' R' U R U2 R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS14', moves: `R U R' U R2 U R' U R U2' R2'`, mirror: false, invert: false },
    { name: 'OLS15', moves: `R U R' U2 R2 D R' U2 R D' R' U' R'`, mirror: false, invert: false },
    { name: 'OLS16', moves: `R U' R' U2 R U2 R' U R U' R' U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS17', moves: `U D' R' D R U R' D' R D`, mirror: false, invert: false },
    { name: 'OLS18', moves: `U2 R U R' U' R U' R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS19', moves: `R U R D R' U2 R D' R' U R'`, mirror: false, invert: false },
    { name: 'OLS20', moves: `U R' F R U R U' R' F' R U R'`, mirror: false, invert: false },
    { name: 'OLS21', moves: `U2 R U R' U' R U' R' U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS22', moves: `R U2 R' U2 R' F' R U R U' R' F`, mirror: false, invert: false },
    { name: 'OLS23', moves: `U R U' R' U' R U2' R'`, mirror: false, invert: false },
    { name: 'OLS24', moves: `U R U' R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS25', moves: `U2 R U' R U2 R' U' R U' R2'`, mirror: false, invert: false },
    { name: 'OLS26', moves: `U R U' R2 D' R U2 R' D R2 U' R'`, mirror: false, invert: false },
    { name: 'OLS27', moves: `F' R U2 R' U' R U' R' F`, mirror: false, invert: false },
    { name: 'OLS28', moves: `U' R' D' R U2 R' D R2 U' R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS29', moves: `R U R2 D' R U2 R' D R2 U R'`, mirror: false, invert: false },
    { name: 'OLS30', moves: `U' R' U2 R U R U' R2 U2 R2 U' R'`, mirror: false, invert: false },
    { name: 'OLS31', moves: `U2 R U' R2' U2' R U R' U R2 U R'`, mirror: false, invert: false },
    { name: 'OLS32', moves: `D R' U' R U2 R' U' R D'`, mirror: false, invert: false },
    { name: 'OLS33', moves: `R' F' R U R U' R' F U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS34', moves: `U' R2 U R' U R U2' R' U R'`, mirror: false, invert: false },
    { name: 'OLS35', moves: `U R U' R' U' F' R U2' R' U2 R' F R`, mirror: false, invert: false },
    { name: 'OLS36', moves: `U' R U2 R' U' R U R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS37', moves: `R U' R' U2 R U2 R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS38', moves: `U2 R U' R' U2 R U2 R' U R U' R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS39', moves: `U' L U' R U R' L' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS40', moves: `U R U' R' U' R' U' R2 U' R2 U2 R`, mirror: false, invert: false },
    { name: 'OLS41', moves: `U R U' R' U' R U' R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS42', moves: `U' R U R' U R U R' U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS43', moves: `U R U' R' U2 R2 D R' U' R D' R2'`, mirror: false, invert: false },
    { name: 'OLS44', moves: `U R' D' R U R' D R`, mirror: false, invert: false },
    { name: 'OLS45', moves: `U' R U R2' D' r U2 r' D R`, mirror: false, invert: false },
    { name: 'OLS46', moves: `U R U2' R' U R U2' R' U R U2' R'`, mirror: false, invert: false },
    { name: 'OLS47', moves: `U R U2' R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS48', moves: `U2 R U R' U' R' F' R U R U' R' F`, mirror: false, invert: false },
    { name: 'OLS49', moves: `F R U R' U' R' F' R U' R U R'`, mirror: false, invert: false },
    { name: 'OLS50', moves: `R U2' R' U2 R U R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS51', moves: `U2 R U2 R' U R' F' R U2 R U2 R' F R U R'`, mirror: false, invert: false },
    { name: 'OLS52', moves: `U' R U' R' U R U R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS53', moves: `U' R' D' R U2 R' D R2 U2' R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS54', moves: `R U2' R' U R U2' R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS55', moves: `R U' R' U2 R U R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS56', moves: `U2 F' R' U2' R U R' U R U F`, mirror: false, invert: false },
    { name: 'OLS57', moves: `U' R' D' R U R' D R U R U2 R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS58', moves: `U2 F' U' R U R' U R U2' R' U2 F`, mirror: false, invert: false },
    { name: 'OLS59', moves: `R' U' D' R U' R' U2 D R`, mirror: false, invert: false },
    { name: 'OLS60', moves: `U2 R U' R2' F' R U2 R U2' R' F R U R'`, mirror: false, invert: false },
    { name: 'OLS61', moves: `R U' R' U R U' R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS62', moves: `U' R U R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS63', moves: `R U' R' U2 R U' R2 D' R U R' D R`, mirror: false, invert: false },
    { name: 'OLS64', moves: `U R U2 R' U' L R U' R' U L'`, mirror: false, invert: false },
    { name: 'OLS65', moves: `U R U2 R' U R U' R' U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS66', moves: `U' R U R' U2 R U2 R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS67', moves: `R U2 R' U R U2 L U' R' U L'`, mirror: false, invert: false },
    { name: 'OLS68', moves: `U R' D' R U R' D R2 U R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS69', moves: `U2 R U2 R' U' R U R' U2 R U' R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS70', moves: `U2 R U' R' U2 R U R' U2 R U' R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS71', moves: `R2' U2' R2 U' R2' U' R2`, mirror: false, invert: false },
    { name: 'OLS72', moves: `U' R U2' R' U' R U2' R' U' R U2' R'`, mirror: false, invert: false },
    { name: 'OLS73', moves: `R U' R' U R U R' U2 R U2' R'`, mirror: false, invert: false },
    { name: 'OLS74', moves: `R U' R' U R U R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS75', moves: `R F' r U R' U' r' F`, mirror: false, invert: false },
    { name: 'OLS76', moves: `R U' R' U L U' R U R' L'`, mirror: false, invert: false },
    { name: 'OLS77', moves: `U R U R' U' L U' R U R' L'`, mirror: false, invert: false },
    { name: 'OLS78', moves: `F' R U R' U R U2 R' F`, mirror: false, invert: false },
    { name: 'OLS79', moves: `U R U2' R' U2 R U2' R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS80', moves: `R U R2' D' R U' R' D R U2 R U2' R'`, mirror: false, invert: false },
    { name: 'OLS81', moves: `U2 R U2 R' U' R U' R' U R U' R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS82', moves: `U' F' R U R' U' R' F R2 U2 R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS83', moves: `U' R U R' U' R U2' R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS84', moves: `U' R U' R' U R U' R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS85', moves: `R U' R' U' R U' R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS86', moves: `U R U R' U R U' R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS87', moves: `U2 L' U2 R2' U2' R2 U' R2' U' R2 L`, mirror: false, invert: false },
    { name: 'OLS88', moves: `U' R U R' U' R U2 R' U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS89', moves: `U R F' U R' U R U2 F R'`, mirror: false, invert: false },
    { name: 'OLS90', moves: `R U2' R' U2 R U' R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS91', moves: `U F' U L' U2 L U' L' U' L U F`, mirror: false, invert: false },
    { name: 'OLS92', moves: `U2 R U' R' U2 R2 D R' U2 R D' R' U R'`, mirror: false, invert: false },
    { name: 'OLS93', moves: `U' R U' R' U R U' R' U R U R' U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS94', moves: `U' R U2' R' U' R U2' R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS95', moves: `U R U R' U' R U R' U2 R U2' R'`, mirror: false, invert: false },
    { name: 'OLS96', moves: `U R U R' U2 F R U R' U' R' F R`, mirror: false, invert: false },
    { name: 'OLS97', moves: `U2 R U R' U2 R U2' R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS98', moves: `U R' D' R U R' D R2 U' R'`, mirror: false, invert: false },
    { name: 'OLS99', moves: `R2 D' R2 U R U' R' U R' D R2 U' R'`, mirror: false, invert: false },
    { name: 'OLS100', moves: `U R' F' R U2 R U' R' U R U2 R' F`, mirror: false, invert: false },
    { name: 'OLS101', moves: `U R' D' R U' R' D R U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS102', moves: `U R U' R' U2 R' U' R2 U' R2 U2 R`, mirror: false, invert: false },
    { name: 'OLS103', moves: `R U' R' U' R U2 R' U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS104', moves: `U R U' R' U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS105', moves: `U2 R U' R' U' R U' R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS106', moves: `R U R' U R2 U2 R2 U' R2 U' R2`, mirror: false, invert: false },
    { name: 'OLS107', moves: `U' R U R' U' R U' R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS108', moves: `U R U' R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS109', moves: `U R U' R' U R U R' U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS110', moves: `R2 U R' U R U' R' U R U2 R2`, mirror: false, invert: false },
    { name: 'OLS111', moves: `U R' D' R U R' D R U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS112', moves: `U R U2 R' U2 R U' R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS113', moves: `R U' R2 D' R U2 R' D R U R U' R'`, mirror: false, invert: false },
    { name: 'OLS114', moves: `U R' D' R U2 R' D R2 U2 R'`, mirror: false, invert: false },
    { name: 'OLS115', moves: `U R U' R' U R' D' R U R' D R2 U2 R`, mirror: false, invert: false },
    { name: 'OLS116', moves: `R U2 R' U' R U2 R' U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS117', moves: `U L R U' R' U R U' R' U L'`, mirror: false, invert: false },
    { name: 'OLS118', moves: `U R U' R2 F R U R U' R' F'`, mirror: false, invert: false },
    { name: 'OLS119', moves: `U R U' R' U2 R U' R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS120', moves: `U R U' R' L' U R U' R' L`, mirror: false, invert: false },
    { name: 'OLS121', moves: `U' R2 D R' U' R D' R' U2 R' U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS122', moves: `U' R' D' R U' R' D R2 U2 R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS123', moves: `U2 R U2 R' U2 R U' R2 D' R U2 R' D R`, mirror: false, invert: false },
    { name: 'OLS124', moves: `U' R U' R2 D' R U' R' D R U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS125', moves: `F' R U2 R' U2 R' F R2 U R'`, mirror: false, invert: false },
    { name: 'OLS126', moves: `R U R2 D' R U' R' D R`, mirror: false, invert: false },
    { name: 'OLS127', moves: `D' R' D R U2 R' D' R U2 D R U R'`, mirror: false, invert: false },
    { name: 'OLS128', moves: `R2 U R' U R U2 R2 U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS129', moves: `U' R U2 R' U R U2 R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS130', moves: `R U2 R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS131', moves: `U' R U R' U2 R U R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS132', moves: `U R U R' U' R U2 R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS133', moves: `L' U R U' L U2 R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS134', moves: `R U2 L U' R' U L'`, mirror: false, invert: false },
    { name: 'OLS135', moves: `U L' R U R' U' R U R' U' L`, mirror: false, invert: false },
    { name: 'OLS136', moves: `U R U R' U L R U' R' U L'`, mirror: false, invert: false },
    { name: 'OLS137', moves: `U' R U R' U' R2 D R' U R D' R' U R'`, mirror: false, invert: false },
    { name: 'OLS138', moves: `U' F R U' R' U R U R2 F' R2 U R'`, mirror: false, invert: false },
    { name: 'OLS139', moves: `R U2 R' U2 R U2 R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS140', moves: `U' R U R' U2 R U' R2 D' R U R' D R`, mirror: false, invert: false },
    { name: 'OLS141', moves: `U' R U2 R2 D' R U2 R' D R`, mirror: false, invert: false },
    { name: 'OLS142', moves: `U2 L U' R U R' U' R U R' L'`, mirror: false, invert: false },
    { name: 'OLS143', moves: `U R U R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS144', moves: `U R U R' U' R U' R' U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS145', moves: `U S R2 S' R2 U R' U' R U R2 U R'`, mirror: false, invert: false },
    { name: 'OLS146', moves: `R U2 R' U2 R U' R' U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS147', moves: `U R U2 R D R' U' R D' R2 U' R U R'`, mirror: false, invert: false },
    { name: 'OLS148', moves: `U R U2 R' U2 R U' R' U R U R' U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS149', moves: `R2 D R' U R D' R' U R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS150', moves: `U R U2 R' U R U' R2 D' R U R' D R`, mirror: false, invert: false },
    { name: 'OLS151', moves: `U2 R U2 R' U2 R2 D R' U2 R D' R U R'`, mirror: false, invert: false },
    { name: 'OLS152', moves: `R' U' S R2' S' R2 U R`, mirror: false, invert: false },
    { name: 'OLS153', moves: `U' R U' R2 D' R U2 R' D R2 U R'`, mirror: false, invert: false },
    { name: 'OLS154', moves: `U R' F' R U R U' R' F`, mirror: false, invert: false },
    { name: 'OLS155', moves: `U R U' R' U R U2 R' U R U2 R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS156', moves: `U2 R' U2 R F' R U R' U' R' F U2 R`, mirror: false, invert: false },
    { name: 'OLS157', moves: `R' D' R U' R' D R U R U R'`, mirror: false, invert: false },
    { name: 'OLS158', moves: `U R F R' U R U' F' R'`, mirror: false, invert: false },
    { name: 'OLS159', moves: `F' R U R' U' R' F R2 U R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS160', moves: `U' R U2 R' U R U' R' U' R U' R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS161', moves: `R' D' R U2 R' D R U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS162', moves: `U2 D R' U' R U2 R' U' R D' R U R'`, mirror: false, invert: false },
    { name: 'OLS163', moves: `F' R U R' U' R' F R`, mirror: false, invert: false },
    { name: 'OLS164', moves: `R F U R' U' R F' U R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS165', moves: `U S' R U' R' f R' F' R`, mirror: false, invert: false },
    { name: 'OLS166', moves: `U R U2 R' U R U2 R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS167', moves: `U' R U2 R' F' R U2 R' U' R U' R' F`, mirror: false, invert: false },
    { name: 'OLS168', moves: `S' R U' R' f R' F' R`, mirror: false, invert: false },
    { name: 'OLS169', moves: `R U' R' U2 R U' R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS170', moves: `U' R' U' R D' R U' R' D R' U2 R`, mirror: false, invert: false },
    { name: 'OLS171', moves: `U' R U R' U2 R U2 R' U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS172', moves: `R' F R f' R U R' S`, mirror: false, invert: false },
    { name: 'OLS173', moves: `U' R U2 R' U R U' R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS174', moves: `R U' R2' D' R U R' D R2 U R'`, mirror: false, invert: false },
    { name: 'OLS175', moves: `U' R U R' U2 R U2 R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS176', moves: `U' R U' R D R' U2 R D' R' U R'`, mirror: false, invert: false },
    { name: 'OLS177', moves: `U R U' R2' D' R U' R' D R2 U R'`, mirror: false, invert: false },
    { name: 'OLS178', moves: `R U' R' U' R U R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS179', moves: `U2 R' D' R U' R' D R U R U' R'`, mirror: false, invert: false },
    { name: 'OLS180', moves: `U2 R U2 R' U R U R' U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS181', moves: `U2 R U' R' F' R U R' U R U2 R' F`, mirror: false, invert: false },
    { name: 'OLS182', moves: `R U' R' U R U R' U' R' D' R U R' D R`, mirror: false, invert: false },
    { name: 'OLS183', moves: `R U R2 D R' U2 R D' R' U2 R2`, mirror: false, invert: false },
    { name: 'OLS184', moves: `U2 R U' R U2 R2 U' R2 U' R2`, mirror: false, invert: false },
    { name: 'OLS185', moves: `U2 R U2 R' U R U R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS186', moves: `R U2 R' U2 F' R U R' U' R' F R`, mirror: false, invert: false },
    { name: 'OLS187', moves: `R U2 R' U' R' F' R U R U' R' F`, mirror: false, invert: false },
    { name: 'OLS188', moves: `U2 R' D' R U' R' D R U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS189', moves: `U' R U2 R D R' U' R D' R' U R'`, mirror: false, invert: false },
    { name: 'OLS190', moves: `R U R' U' R U2 R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS191', moves: `U' R' F R U R U' R' F' U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS192', moves: `U R U R' U R' D' R U' R' D R U R U' R'`, mirror: false, invert: false },
    { name: 'OLS193', moves: `U2 R U2 R' U2 L' U R U' L U' R'`, mirror: false, invert: false },
    { name: 'OLS194', moves: `R U R' U R U R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS195', moves: `U2 R U2 R' U' R U' R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS196', moves: `U2 R U R' U2 R' D' R U R' D R2 U' R'`, mirror: false, invert: false },
    { name: 'OLS197', moves: `U2 R U R' U2 R U' R' U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS198', moves: `R U2 R' U R F U' R' U2 R U F' R'`, mirror: false, invert: false },
    { name: 'OLS199', moves: `R U R' U' R U2 R' U R U' R' U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS200', moves: `U2 R U R' U2 R U' R2 F R U R U' R' F'`, mirror: false, invert: false },
    { name: 'OLS201', moves: `R U' R' U' R U R' U2 R U' R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS202', moves: `U2 R U R' U2 R U' R' r' F R F' M'`, mirror: false, invert: false },
    { name: 'OLS203', moves: `R U' R2 F R U R U' R' F' U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS204', moves: `U2 R U R' U2 R U' R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS205', moves: `U' R U2 R' U2 R U' R' U R U' R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS206', moves: `U2 R U' R' D' R' D R U2 R' D' R D`, mirror: false, invert: false },
    { name: 'OLS207', moves: `U' R U' R' U2 R U R2 D' R U' R' D R`, mirror: false, invert: false },
    { name: 'OLS208', moves: `U' R U' R' U2 R2 U R' U R U2 R' U2 R'`, mirror: false, invert: false },
    { name: 'OLS209', moves: `U2 R' D' R U2 R' D R2 U R'`, mirror: false, invert: false },
    { name: 'OLS210', moves: `U2 R' U2 R2 U R' U' R' U2 R`, mirror: false, invert: false },
    { name: 'OLS211', moves: `U R U2 R' U R' U2 R2 U R2 U R`, mirror: false, invert: false },
    { name: 'OLS212', moves: `U2 D R2 U2 R' U R U R2 D'`, mirror: false, invert: false },
    { name: 'OLS213', moves: `R U2 R' U2 R U R2 D' R U' R' D R`, mirror: false, invert: false },
    { name: 'OLS214', moves: `U2 R U R' U F' R U R' U' R' F R`, mirror: false, invert: false },
    { name: 'OLS215', moves: `U2 R' U2 R2 U R2 U R`, mirror: false, invert: false },
    { name: 'OLS216', moves: `U2 R2 D R' U2 R D' R' U R'`, mirror: false, invert: false },
    { name: 'OLS217', moves: `U' R U' R' U2 R U2 R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS218', moves: `U2 R U R' U R' D' R U2 R' D R U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS219', moves: `U2 R U' R' U2 R U R' U' R U' R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS220', moves: `U2 R U' R' U R U' R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS221', moves: `U R U R' U R' U2 R2 U R2 U R`, mirror: false, invert: false },
    { name: 'OLS222', moves: `U2 R U' R' U R U' R' U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS223', moves: `U2 R U R' U2 R' F' R U R U' R' F`, mirror: false, invert: false },
    { name: 'OLS224', moves: `U' R U R' U2 R2 D R' U2 R D' R' U R'`, mirror: false, invert: false },
    { name: 'OLS225', moves: `U2 R' D' R U2 R' D R2 U2 R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS226', moves: `U' R U R' U2 R' U2 R2 U R2 U R`, mirror: false, invert: false },
    { name: 'OLS227', moves: `U' R U' R' U' R U R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS228', moves: `R U2 R' U' R U R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS229', moves: `U2 R U2 R' U2 R U2 R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS230', moves: `R' U' R U' R' U2 R2 U R'`, mirror: false, invert: false },
    { name: 'OLS231', moves: `U2 R U D' R U' R' U' R U2 R' D R'`, mirror: false, invert: false },
    { name: 'OLS232', moves: `U2 R U2 R' U2 R U2 R' U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS233', moves: `U L' U2 R U' R' U2 L`, mirror: false, invert: false },
    { name: 'OLS234', moves: `U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS235', moves: `U2 R' F R U R U' R' F'`, mirror: false, invert: false },
    { name: 'OLS236', moves: `U' R2 D R' U' R D' R2`, mirror: false, invert: false },
    { name: 'OLS237', moves: `U' R U' R' U R' U' R U' R' U2 R`, mirror: false, invert: false },
    { name: 'OLS238', moves: `U R' D' R U2 R' D R2 U' R'`, mirror: false, invert: false },
    { name: 'OLS239', moves: `U' R U R' U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS240', moves: `U' R' D' R U R' D R2 U2 R'`, mirror: false, invert: false },
    { name: 'OLS241', moves: `U2 R' F' R U2 R U2 R' F`, mirror: false, invert: false },
    { name: 'OLS242', moves: `U' R U2 R' U2 L R U' R' U L'`, mirror: false, invert: false },
    { name: 'OLS243', moves: `R' U' R U R U2 R' U2 R' U2 R`, mirror: false, invert: false },
    { name: 'OLS244', moves: `R U2 R'`, mirror: false, invert: false },
    { name: 'OLS245', moves: `U' L' U2 R U' R' U' R U' R' L`, mirror: false, invert: false },
    { name: 'OLS246', moves: `R2 D R' U2 R D' R2`, mirror: false, invert: false },
    { name: 'OLS247', moves: `U2 L' U R U' R' L`, mirror: false, invert: false },
    { name: 'OLS248', moves: `R U' R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS249', moves: `F' R U2 R' U2 R' F R`, mirror: false, invert: false },
    { name: 'OLS250', moves: `U' R U R2 U' R2 U' R2 U2 R`, mirror: false, invert: false },
    { name: 'OLS251', moves: `R' U' R2 U' R2 U2 R`, mirror: false, invert: false },
    { name: 'OLS252', moves: `U' R U' R' U' R U R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS253', moves: `U' R U R D R' U2 R D' R2`, mirror: false, invert: false },
    { name: 'OLS254', moves: `R U' R' U R U' R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS255', moves: `U' R U' R' U R U2 R' U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS256', moves: `R U' R D R' U' R D' R2`, mirror: false, invert: false },
    { name: 'OLS257', moves: `U2 R2 U R' U R' U' R U R U2 R2`, mirror: false, invert: false },
    { name: 'OLS258', moves: `R U2 R' U R U R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS259', moves: `U' R U R' U' R U R' U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS260', moves: `R U' R' U2 R U' R' U R U2 R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS261', moves: `U' R U' R' U2 R U' R' U R U2 R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS262', moves: `U' R U2 R' U R U2 R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS263', moves: `U R U R' U2 R U' R' U R U R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS264', moves: `U R U' R' U R U2 R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS265', moves: `S R2 S' R2 U R' U' R U R`, mirror: false, invert: false },
    { name: 'OLS266', moves: `U R2 D R' U R D' R2`, mirror: false, invert: false },
    { name: 'OLS267', moves: `U R U R' U2 R U R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS268', moves: `U' R U R' U R U' R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS269', moves: `U2 R U2 R' U R U' R' U2 R U' R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS270', moves: `U R U2 R' U2 R U' R' U R U2 R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS271', moves: `U2 R U2 R' U2 R U R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS272', moves: `U' R U R' U R2 D R' U R D' R2`, mirror: false, invert: false },
    { name: 'OLS273', moves: `U2 R U F R' U R U' F' R'`, mirror: false, invert: false },
    { name: 'OLS274', moves: `U R U' R2 U2 R U R' U R2 U' R'`, mirror: false, invert: false },
    { name: 'OLS275', moves: `U R U' R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS276', moves: `U R2 U2 R2 U' R2 U' R2 U' R U R'`, mirror: false, invert: false },
    { name: 'OLS277', moves: `R' D' R U R' D R2 U' R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS278', moves: `R2 U R' U R U2 R2`, mirror: false, invert: false },
    { name: 'OLS279', moves: `R U R' U R U2 R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS280', moves: `R U' R' U R2 U R' U R U2 R2`, mirror: false, invert: false },
    { name: 'OLS281', moves: `U R U' R' U R U' R' U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS282', moves: `U2 R U2 R' U2 R U R' U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS283', moves: `U' R U' R' U' R U' R' U R U2 R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS284', moves: `U R U2 R' U' R U' R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS285', moves: `U R2 D R' U2 R D' R' U' R'`, mirror: false, invert: false },
    { name: 'OLS286', moves: `R' U' R U2 R U' R' U R U R2 U' R`, mirror: false, invert: false },
    { name: 'OLS287', moves: `U2 R U' R' U R U2 R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS288', moves: `U2 R U' R2' D' R U2 R' D R`, mirror: false, invert: false },
    { name: 'OLS289', moves: `U' R U' R' U' R U' R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS290', moves: `R U2 R' U' R U' R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS291', moves: `U R2 D R' U2 R D' R2' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS292', moves: `R U R' U' R U' R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS293', moves: `U2 R U R' U R U2 R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS294', moves: `R U' R' U R' U2 R U R' U R2 U R'`, mirror: false, invert: false },
    { name: 'OLS295', moves: `R U R' U R2 U R' U R U2 R' U R'`, mirror: false, invert: false },
    { name: 'OLS296', moves: `U2 R U2 R' U2 R U R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS297', moves: `U2 R U R' U2' R U R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS298', moves: `R U' R' U' R F R' U R U' F' U' R'`, mirror: false, invert: false },
    { name: 'OLS299', moves: `U2 R U R' U R2 U R' U R U2 R' U2 R'`, mirror: false, invert: false },
    { name: 'OLS300', moves: `U' R F R' U R U' F' U' R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS301', moves: `R2 U2' R' U' R U' R2`, mirror: false, invert: false },
    { name: 'OLS302', moves: `U R' U' R U' R' U2 R U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS303', moves: `U' R2 U2' R' U' R U' R' U R'`, mirror: false, invert: false },
    { name: 'OLS304', moves: `U R U R D R' U2 R D' R2 U' R U R'`, mirror: false, invert: false },
    { name: 'OLS305', moves: `U2 R F R' U R U' F' U' R'`, mirror: false, invert: false },
    { name: 'OLS306', moves: `U2 R U2' R' U2 R U' R2' D' R U R' D R`, mirror: false, invert: false },
    { name: 'OLS307', moves: `U2 R U2' R' U R U' R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS308', moves: `U' R' U2' R U R' U R2 U R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS309', moves: `U2 R' U' R U' R' U2 R2 U2' R'`, mirror: false, invert: false },
    { name: 'OLS310', moves: `U2 R' U' R U' R' U R2 U' R2' U2' R`, mirror: false, invert: false },
    { name: 'OLS311', moves: `U' R U R2' U2' R U R' U R2 U R'`, mirror: false, invert: false },
    { name: 'OLS312', moves: `R U' R' U R2 U2 R' U' R U' R2`, mirror: false, invert: false },
    { name: 'OLS313', moves: `R' U2' R U R' U R2 U R'`, mirror: false, invert: false },
    { name: 'OLS314', moves: `U2 R U2 R' U' R U2 R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS315', moves: `R2 D R' U R D' R2 U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS316', moves: `U2 R U' R' U' R U R' U R' D' R U R' D R`, mirror: false, invert: false },
    { name: 'OLS317', moves: `U2 R U2 R' U R' D' R U' R' D R U' R U R'`, mirror: false, invert: false },
    { name: 'OLS318', moves: `U' R2 D R' U2 R D' R2 U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS319', moves: `U R U2 R' U' R U R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS320', moves: `U' R U' R' U2 R U' R' U' R U R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS321', moves: `U2 R2 D R' U R D' R' U2 R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS322', moves: `U' R U2 R' U' R U R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS323', moves: `U2 R U' R D R' U' R D' R2 U' R U R'`, mirror: false, invert: false },
    { name: 'OLS324', moves: `U R U' R' U2 R U2 R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS325', moves: `U2 R U' R' U2 R2 D R' U R D' R' U R'`, mirror: false, invert: false },
    { name: 'OLS326', moves: `U2 R U R' U' R U R2 D' R U' R' D R`, mirror: false, invert: false },
    { name: 'OLS327', moves: `R2 D R' U R D' R2 U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS328', moves: `U2 R U2 R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS329', moves: `U R' U2 R2 U R2 U R2 U R'`, mirror: false, invert: false },
    { name: 'OLS330', moves: `U R U2 R' U' R U R' U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS331', moves: `U2 R U R' U' R U2 R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS332', moves: `U2 R U2 R' U R' D' r U2 r' D R`, mirror: false, invert: false },
    { name: 'OLS333', moves: `U' R U2 R' U R U' F R' U R U' F' R'`, mirror: false, invert: false },
    { name: 'OLS334', moves: `R U R' U' R U R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS335', moves: `U R U2 R' U R U' R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS336', moves: `U2 R U2 R' U' R U' R' U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS337', moves: `U R U2 R' U' L U' R U R' L'`, mirror: false, invert: false },
    { name: 'OLS338', moves: `U R U' R' U2 R U2 R' U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS339', moves: `U' R U2 R' U' R U R' U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS340', moves: `R U R' U' R U R' U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS341', moves: `U R U' R' U2 R2 U R' U R U2 R' U R'`, mirror: false, invert: false },
    { name: 'OLS342', moves: `U2 R U' R' U R U' R' U' R U R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS343', moves: `R U' R' U R U' R' U2 R U' R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS344', moves: `U2 R2 U R' U R U2 R' U R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS345', moves: `U R U R' F' R U R' U' R' F R U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS346', moves: `U2 R' D' R U2 R' D R U R U' R'`, mirror: false, invert: false },
    { name: 'OLS347', moves: `U' R U R' U R U' R' U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS348', moves: `U2 R U' R' U' R U2 R2 F R U R U' R' F'`, mirror: false, invert: false },
    { name: 'OLS349', moves: `U2 R U R' U R' D' R U R' D R2 U' R'`, mirror: false, invert: false },
    { name: 'OLS350', moves: `U' R U2 R2 D' R U2 R' D R2 U R'`, mirror: false, invert: false },
    { name: 'OLS351', moves: `U R U2 R' U' R U' R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS352', moves: `U2 R U' R' U' R U2 R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS353', moves: `U2 R U' R' U' R U R' U2 R U' R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS354', moves: `U R U2 R2 D' R U2 R' D R2 U' R'`, mirror: false, invert: false },
    { name: 'OLS355', moves: `U R U2 R2 D' R U' R' D R2 U2 R'`, mirror: false, invert: false },
    { name: 'OLS356', moves: `U2 R U' R' U' R U2 R' U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS357', moves: `U2 R' D' R U2 R' D R U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS358', moves: `U' R U R' U R U' R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS359', moves: `U R U2 R' U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS360', moves: `U2 R U R' U R U' R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS361', moves: `U' R U' R' U F' R U R' U' R' F R`, mirror: false, invert: false },
    { name: 'OLS362', moves: `U R U2 R' U R' F R U R U' R' F'`, mirror: false, invert: false },
    { name: 'OLS363', moves: `R U' R' U2 R U R' U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS364', moves: `R U' R' U R U2 R' F' R U R' U' R' F R`, mirror: false, invert: false },
    { name: 'OLS365', moves: `U2 R U' R' U2 R U' R' U R U' R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS366', moves: `U R U2 R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS367', moves: `U2 R U R' U R U' R' U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS368', moves: `U R U2 R D R' U2 R D' R' U' R'`, mirror: false, invert: false },
    { name: 'OLS369', moves: `U R U R' U R U' R' U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS370', moves: `U2 R' U' R U' R' U2 R2 U R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS371', moves: `U' R' U2 R2 U R2 U R U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS372', moves: `R' U' R U' R U R2 U R`, mirror: false, invert: false },
    { name: 'OLS373', moves: `R2 D R' U' R D' R2 U' R U R'`, mirror: false, invert: false },
    { name: 'OLS374', moves: `U' R U R2 D' R U2 R' D R`, mirror: false, invert: false },
    { name: 'OLS375', moves: `U' R U' R' U R U2 R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS376', moves: `U R U2 R' U' R2 U R' U R U2 R2`, mirror: false, invert: false },
    { name: 'OLS377', moves: `U' R U R' U R U2 R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS378', moves: `U2 R' D' R U R' D R2 U R'`, mirror: false, invert: false },
    { name: 'OLS379', moves: `U R U R' U R U' R D R' U2 R D' R2`, mirror: false, invert: false },
    { name: 'OLS380', moves: `R U2 R' U' R U2 R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS381', moves: `U R U R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS382', moves: `U' R U' R' U2 R U R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS383', moves: `U R U R' U R U2 R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS384', moves: `R U' R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS385', moves: `U R U' R2 D' R U R' D R`, mirror: false, invert: false },
    { name: 'OLS386', moves: `R U' R' U2 R U R D R' U R D' R2`, mirror: false, invert: false },
    { name: 'OLS387', moves: `U' R' U2 R U R' U R U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS388', moves: `U' R U R' U' R U R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS389', moves: `U2 R U' R' U R U R' U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS390', moves: `U2 R2 D R' U R D' R' U R'`, mirror: false, invert: false },
    { name: 'OLS391', moves: `R U' R' U R U' R2 D' R U' R' D R`, mirror: false, invert: false },
    { name: 'OLS392', moves: `R' U' R U' R U R' U' R' U2 R`, mirror: false, invert: false },
    { name: 'OLS393', moves: `U' R' U2 R U R' U R U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS394', moves: `U2 R U2 R' U2 R U' R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS395', moves: `U R U R2 D' R U2 R' D R2 U' R'`, mirror: false, invert: false },
    { name: 'OLS396', moves: `R U R' U2 R U' R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS397', moves: `U R U R' U2 R2 D R' U' R D' R2`, mirror: false, invert: false },
    { name: 'OLS398', moves: `U2 R' D' R U R' D R U R U' R'`, mirror: false, invert: false },
    { name: 'OLS399', moves: `U R U R2 D' R U' R' D R2 U2 R'`, mirror: false, invert: false },
    { name: 'OLS400', moves: `U2 R U2 R' U' R U2 R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS401', moves: `U R U R' U' R U' R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS402', moves: `F R U R' U' R' F' R2 U' R'`, mirror: false, invert: false },
    { name: 'OLS403', moves: `U' R U' R2 F' R U R U' R' F`, mirror: false, invert: false },
    { name: 'OLS404', moves: `U R U R' U' F' R U2 R' U2 R' F R`, mirror: false, invert: false },
    { name: 'OLS405', moves: `U R U R' U2 R U R' U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS406', moves: `U' R U R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS407', moves: `U2 R U' R' U2 R U2 R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS408', moves: `U R U R' L' U2 R U' R' U2 L`, mirror: false, invert: false },
    { name: 'OLS409', moves: `R U' R' U2 R U' R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS410', moves: `U' R2 U2 R2 U' R2 U' R2 U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS411', moves: `U R' U' R U' R' U2 R U' R U R'`, mirror: false, invert: false },
    { name: 'OLS412', moves: `U' R U R' U R U2 R' U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS413', moves: `U' R2 U2 R2 U' R2 U' R' U2 R'`, mirror: false, invert: false },
    { name: 'OLS414', moves: `U F R U R' U' R' F' R U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS415', moves: `U R' D' R U R' D R U R U' R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS416', moves: `U2 R' D' R U R' D R U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS417', moves: `U2 R U R' U' R U R' U' R U2 R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS418', moves: `U' R U R' U R U2 R' U2 R U' R'`, mirror: false, invert: false },
    { name: 'OLS419', moves: `U R' D' R U R' D R U R U' R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS420', moves: `U R U R' U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS421', moves: `U' R U2 R' U' R U' R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS422', moves: `R' D' r U2 r' D R`, mirror: false, invert: false },
    { name: 'OLS423', moves: `U2 R U R' U' R U R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS424', moves: `U2 R U' R' F' R U2 R' U2 R' F R`, mirror: false, invert: false },
    { name: 'OLS425', moves: `L R U' R' U L'`, mirror: false, invert: false },
    { name: 'OLS426', moves: `U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS427', moves: `U2 R U R' U R' U2 R U R' U R`, mirror: false, invert: false },
    { name: 'OLS428', moves: `U2 R U' R2 D' R U' R' D R2 U' R'`, mirror: false, invert: false },
    { name: 'OLS429', moves: `U' L' R U R' U R U' R' U2 L`, mirror: false, invert: false },
    { name: 'OLS430', moves: `U2 R U' R D R' U2 R D' R2'`, mirror: false, invert: false },
    { name: 'OLS431', moves: `U2 R U2 R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS432', moves: `U2 R U' R' U R' D' R U2 R' D R2 U' R'`, mirror: false, invert: false },
    { name: 'OLS433', moves: `R U' R2 D' R U' R' D R`, mirror: false, invert: false },
    { name: 'OLS434', moves: `U2 R U2 R' U R U' R' U R U' R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS435', moves: `U2 R U' R' U' R U R' U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS436', moves: `R U R' U R U' R' U2 R U' R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS437', moves: `R' U2 R U R' U R U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS438', moves: `U2 R U' R' U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS439', moves: `U' R' D' R U2 R' D R U R U R'`, mirror: false, invert: false },
    { name: 'OLS440', moves: `U2 R U2 R' U2 R' D' R U2 R' D R2 U' R'`, mirror: false, invert: false },
    { name: 'OLS441', moves: `R U R' U2 R U R' U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS442', moves: `U2 R U2 R' U R U' R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS443', moves: `U2 R U R2 U2 R U R' U R`, mirror: false, invert: false },
    { name: 'OLS444', moves: `U2 R U2 R D R' U' R D' R2'`, mirror: false, invert: false },
    { name: 'OLS445', moves: `U2 R U2 R' U R U2 R' U R U R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS446', moves: `U2 R U R' U R' U' R U' R' U2 R`, mirror: false, invert: false },
    { name: 'OLS447', moves: `U R U R D R' U R D' R2'`, mirror: false, invert: false },
    { name: 'OLS448', moves: `U2 R U' R' U2 L' U R U' R' L`, mirror: false, invert: false },
    { name: 'OLS449', moves: `U2 R U' R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS450', moves: `U' R U' R' U2 R' D' R U R' D R2 U' R'`, mirror: false, invert: false },
    { name: 'OLS451', moves: `R U R' U R2 D R' U' R D' R2`, mirror: false, invert: false },
    { name: 'OLS452', moves: `R U R' L' U2 R U2 R' U2 L`, mirror: false, invert: false },
    { name: 'OLS453', moves: `R U R' U R U R' U' R U' R'`, mirror: false, invert: false },
    { name: 'OLS454', moves: `R U R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS455', moves: `L U' R U R' L'`, mirror: false, invert: false },
    { name: 'OLS456', moves: `U2 R U' R' U2 R U2 R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS457', moves: `R U R' U2 R U' R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS458', moves: `U L U' R U R' L' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS459', moves: `U F U R U' R' U R U' R2 F' R2 U' R'`, mirror: false, invert: false },
    { name: 'OLS460', moves: `R U R2 U2 R U R' U R2 U2 R'`, mirror: false, invert: false },
    { name: 'OLS461', moves: `U' R U R' U R U2 R' U2 R U2 R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS462', moves: `R U R' U2 R U' R' U R U' R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS463', moves: `U2 R U2 R' U2 R U2 R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS464', moves: `U R U2 R' U R U2 R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS465', moves: `R U R' U2 R2 D R' U2 R D' R2`, mirror: false, invert: false },
    { name: 'OLS466', moves: `U F U R U2 R' U2 R U R2 F' R2 U' R'`, mirror: false, invert: false },
    { name: 'OLS467', moves: `U R U2 R2 D' R U' R' D R`, mirror: false, invert: false },
    { name: 'OLS468', moves: `U R U R' U2 R U2 R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS469', moves: `R U R' U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS470', moves: `U' R U R' F' R U R' U R U2 R' F`, mirror: false, invert: false },
    { name: 'OLS471', moves: `U2 R U R' U R U R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS472', moves: `R U R2 F' R U2 R U2 R' F`, mirror: false, invert: false },
    { name: 'OLS473', moves: `U R U R' U2 R U2 R' U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS474', moves: `U' R U' R' U2 R U' R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS475', moves: `U' R' U' R U R U' R' U2 R' U2 R U R U' R'`, mirror: false, invert: false },
    { name: 'OLS476', moves: `R U R2 D' R U2 R' D R U R U' R'`, mirror: false, invert: false },
    { name: 'OLS477', moves: `U' R U' R2 D' R U R' D R2 U' R'`, mirror: false, invert: false },
    { name: 'OLS478', moves: `R U R' U' R U2 R' U' R U2 R'`, mirror: false, invert: false },
    { name: 'OLS479', moves: `U2 R' F R U R U' R' F' R U' R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS480', moves: `U2 R U' R' U R2 D R' U R D' R2`, mirror: false, invert: false },
    { name: 'OLS481', moves: `U2 R U2 R' U2 R2 D R' U R D' R2`, mirror: false, invert: false },
    { name: 'OLS482', moves: `U R2 D R' U' R D' R2 U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS483', moves: `U' R U2 R2 F' R U2 R U2 R' F`, mirror: false, invert: false },
    { name: 'OLS484', moves: `U' R U2 R' U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS485', moves: `U' R' D' R U' R' D R2 U2 R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS486', moves: `U R U' R' U' R U R' U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS487', moves: `U' R U' R2 D' R U R' D R U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS488', moves: `U' R U2 R' U2 R2 D R' U2 R D' R2`, mirror: false, invert: false },
    { name: 'OLS489', moves: `U' R U2 R' U2 R U' R' U R U2 R'`, mirror: false, invert: false },
    { name: 'OLS490', moves: `U' R U R' U2 R U' R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS491', moves: `U R U' R' U R U' R' U2 R U R'`, mirror: false, invert: false },
    { name: 'OLS492', moves: `U2 R U R' U2 R U' R' U R U2 R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS493', moves: `U2 R U' R U R' U R U2 R2`, mirror: false, invert: false },
    { name: 'OLS494', moves: `U' R U R' L U' R U R' L'`, mirror: false, invert: false },
    { name: 'OLS495', moves: `R U2 R' U R U' R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS496', moves: `U' R U2 R' U R U' R'`, mirror: false, invert: false },
    { name: 'OLS497', moves: `U R U R' U R U2 R' U' R U R'`, mirror: false, invert: false },
    { name: 'OLS498', moves: `U2 R U' R' U R U' R' U R U R'`, mirror: false, invert: false },
    { name: 'OLS499', moves: `U2 R U2 R' U R2 U R' U R U2 R2`, mirror: false, invert: false },
    { name: 'OLS500', moves: `R U2 R' U R U' R' U2 R U2 R'`, mirror: false, invert: false },
    { name: 'OLS501', moves: `U' R' U2 R U R' U' R U R' U R2 U' R'`, mirror: false, invert: false },
    { name: 'OLS502', moves: `R U R' U' R U2 R' U2 R U' R'`, mirror: false, invert: false },
];